### ISSUE TITLE
└🚀 ftrack 2ways Sync

### ISSUE THREAD

**Issue by mkolar** [ynput/ayon-ftrack#126]
[AYON Epics](https://github.com/orgs/ynput/projects/27)

This epic is part of [📂 Prod Trackers 2ways Sync](https://github.com/ynput/AYON-Epics/issues/32)

## Strategy

FTrack addon must support two ways synchronization of all relevant data.
This includes syncronizing:
- [ ] One way sync of User
- [ ] Entity attributes (anatomy and attributes values on entities)
- [ ] Statuses
- [ ] Assignments
- [ ] Comments
- [ ] Links
- [ ] Versions and Reviewables - Multiple reviewables will only be possible in AYON, and ftrack only takes the 1st one. 

For the start we'll only do one way for:
- [ ] Entity hierarchy (anatomy and entities themselves)
- [ ] Users
But with full intention to do two way sync for them in this epic as well

## Generic User Stories
(Applicable for each of the checkbox in the strategy section)
- As an Artist or Lead, when I [do something] in the production tracker, I want the changes to be visible in AYON.
- As an Artist or Lead, when I [do something] in AYON Activity Feed, I the changes to be visible in the production tracker.

* We will probably need multiple sync services for ftrack. 
* We need to be able to create a version without a representation.

**Comment by tanh609** [comment]
Hi @mkolar, would The Assignments Todo linked with this https://github.com/ynput/ayon-ftrack/issues/125?

With regards to a way to implement this, is there a way to add custom attribute to Ayon's users for something link user's ftrack id?

**Comment by dee-ynput** [comment]
@tanh609 
I'm cleaning up stuff and I need to close this issue. Can you repost your question here:
https://github.com/ynput/ayon-ftrack/issues/133

Thanks 🙏 and sorry for the inconvenience!

**Comment by dee-ynput** [comment]
actually...
