### ISSUE TITLE
Add `review` to default settings

### ISSUE THREAD

**Issue by antirotor** [ynput/ayon-ftrack#193]
### Is there an existing issue for this?

- [x] I have searched the existing issues and added correct labels.

## Current Behavior
This PR in **ayon-maya** https://github.com/ynput/ayon-maya/pull/161 cleaned ftrack families. We need to add `review` for Maya (but also for Houdini and Blender).

## Expected Behavior
With default `review` it should upload reviews to ftrack.

### Relevant log output:

```shell

```

**Comment by m-u-r-p-h-y** [comment]
and 3dsmax
